import re
from pathlib import Path
from typing import Any, Dict, List, Optional

from app.database import get_workspace, get_workspace_index

AGENTS_FILENAME = "AGENTS.md"
GENERATED_START = "<!-- BEGIN NORTHCORE GENERATED -->"
GENERATED_END = "<!-- END NORTHCORE GENERATED -->"
USER_NOTES_START = "<!-- BEGIN NORTHCORE USER NOTES -->"
USER_NOTES_END = "<!-- END NORTHCORE USER NOTES -->"
MAX_AGENTS_CONTEXT_CHARS = 16000


def _safe_workspace_agents_path(workspace: Dict[str, Any]) -> Optional[Path]:
    raw_path = str(workspace.get("workspacePath") or "").strip()
    if not raw_path:
        return None
    workspace_root = Path(raw_path).resolve()
    return workspace_root / AGENTS_FILENAME


def _extract_user_notes(existing_content: str) -> str:
    existing = str(existing_content or "")
    match = re.search(
        rf"{re.escape(USER_NOTES_START)}\s*([\s\S]*?)\s*{re.escape(USER_NOTES_END)}",
        existing,
    )
    if match:
        return match.group(1).strip()
    if GENERATED_START not in existing and existing.strip():
        return existing.strip()
    return ""


def _flatten_tree(node: Dict[str, Any], limit: int = 80) -> List[str]:
    lines: List[str] = []

    def walk(item: Dict[str, Any], depth: int = 0) -> None:
        if len(lines) >= limit:
            return
        if item.get("type") == "file" and item.get("path"):
            details = []
            if item.get("size") is not None:
                details.append(f"{item.get('size')} bytes")
            if item.get("mimeType"):
                details.append(str(item.get("mimeType")))
            suffix = f" ({', '.join(details)})" if details else ""
            lines.append(f"- {item['path']}{suffix}")
            return
        for child in item.get("children") or []:
            if isinstance(child, dict):
                walk(child, depth + 1)

    if isinstance(node, dict):
        walk(node)
    return lines


def _render_feature_map(feature_map: Dict[str, Any]) -> str:
    if not feature_map:
        return "- 暂无明确功能分组。"
    sections = []
    for name, feature in list(feature_map.items())[:30]:
        if not isinstance(feature, dict):
            continue
        lines = [f"### {name}"]
        description = str(feature.get("description") or "").strip()
        if description:
            lines.append(description)
        for label, key in (
            ("入口文件", "entryFiles"),
            ("核心文件", "files"),
            ("运行时文件", "runtimeFiles"),
            ("配置文件", "configFiles"),
            ("样式文件", "styleFiles"),
            ("测试文件", "testFiles"),
            ("关联 Artifact", "artifacts"),
        ):
            values = [str(item) for item in feature.get(key) or [] if str(item or "").strip()]
            if values:
                lines.append(f"- {label}: {', '.join(values[:12])}")
        sections.append("\n".join(lines))
    return "\n\n".join(sections) if sections else "- 暂无明确功能分组。"


def _render_artifacts(artifact_map: Dict[str, Any]) -> str:
    if not artifact_map:
        return "- 暂无 Artifact 映射。"
    lines = []
    for artifact_id, artifact in list(artifact_map.items())[:30]:
        if not isinstance(artifact, dict):
            continue
        title = artifact.get("title") or artifact_id
        file_path = artifact.get("filePath") or "-"
        artifact_type = artifact.get("type") or "-"
        lines.append(f"- {title} ({artifact_type}) -> {file_path}")
    return "\n".join(lines)


def _render_recent_changes(recent_changes: List[Dict[str, Any]]) -> str:
    if not recent_changes:
        return "- 暂无最近变更。"
    lines = []
    for change in recent_changes[:10]:
        run_id = change.get("runId") or "-"
        paths = [
            str(item.get("path") or "")
            for item in change.get("files") or []
            if isinstance(item, dict) and str(item.get("path") or "").strip()
        ]
        if paths:
            lines.append(f"- {run_id}: {', '.join(paths[:12])}")
    return "\n".join(lines) if lines else "- 暂无最近变更。"


def _build_generated_section(workspace_id: str, index: Optional[Dict[str, Any]]) -> str:
    index = index or {}
    tree_lines = _flatten_tree(index.get("tree") or {})
    summary = str(index.get("summary") or "").strip()
    if not summary:
        summary = "该工作区还没有足够的索引信息。请先查看文件树和用户需求，再谨慎创建或修改文件。"
    return "\n".join([
        "# AGENTS.md",
        "",
        "This file is generated by NorthCore to help coding agents understand this workspace.",
        "",
        "## Workspace Summary",
        summary,
        "",
        "## Project Structure",
        "\n".join(tree_lines) if tree_lines else "- 暂无已跟踪文件。",
        "",
        "## Feature Map",
        _render_feature_map(index.get("featureMap") or {}),
        "",
        "## Artifacts",
        _render_artifacts(index.get("artifactMap") or {}),
        "",
        "## Recent Changes",
        _render_recent_changes(index.get("recentChanges") or []),
        "",
        "## Collaboration Guidance",
        "- Treat this file as project context, not as application source code.",
        "- Read relevant source files before editing existing functionality.",
        "- Prefer updating existing files over creating duplicate implementations.",
        "- Keep generated artifacts, source files, and configuration changes consistent.",
        "",
        f"Workspace ID: {workspace_id}",
        f"Index status: {index.get('status') or 'missing'}",
        f"Index version: {index.get('version') or 0}",
    ])


def build_workspace_agents_markdown(workspace_id: str, existing_content: str = "") -> str:
    user_notes = _extract_user_notes(existing_content)
    generated = _build_generated_section(workspace_id, get_workspace_index(workspace_id))
    return "\n".join([
        GENERATED_START,
        generated.strip(),
        GENERATED_END,
        "",
        USER_NOTES_START,
        user_notes,
        USER_NOTES_END,
        "",
    ])


def write_workspace_agents_file(workspace_id: str) -> Optional[Dict[str, Any]]:
    workspace = get_workspace(workspace_id)
    if not workspace:
        return None
    path = _safe_workspace_agents_path(workspace)
    if not path:
        return None
    path.parent.mkdir(parents=True, exist_ok=True)
    existing = path.read_text(encoding="utf-8") if path.exists() else ""
    content = build_workspace_agents_markdown(workspace_id, existing)
    path.write_text(content, encoding="utf-8")
    return {
        "workspaceId": workspace_id,
        "path": AGENTS_FILENAME,
        "absolutePath": str(path),
        "content": content,
    }


def ensure_workspace_agents_file(workspace: Dict[str, Any]) -> Optional[Dict[str, Any]]:
    workspace_id = str(workspace.get("id") or "").strip()
    if not workspace_id:
        return None
    return write_workspace_agents_file(workspace_id)


def read_workspace_agents_context(workspace_id: Optional[str]) -> str:
    if not workspace_id:
        return ""
    workspace = get_workspace(workspace_id)
    path = _safe_workspace_agents_path(workspace) if workspace else None
    if path and path.exists() and path.is_file():
        content = path.read_text(encoding="utf-8", errors="replace").strip()
        if content:
            return "[Workspace AGENTS.md]\n" + content[:MAX_AGENTS_CONTEXT_CHARS]

    from app.services.workspace_index_service import workspace_index_brief

    fallback = workspace_index_brief(workspace_id)
    return "[Workspace AGENTS.md fallback]\n" + fallback if fallback else ""
